module.exports = {
    HOUR: 3600,
    DEFAULT_SLICE: 30,
    DEFAULT_TITLE: "Test",
    DEFAULT_TOKEN_GOAL: 5,
    DEFAULT_MAX_TOKENS: 10,
    DEFAULT_STARTDATE_SHIFT: 2,
    DEFAULT_DEADLINE_SHIFT: 6,
    DEFAULT_VALUE: 1
}