module.exports = {
    HOUR: 3600,
    DEFAULT_SLICE: 30,
    DEFAULT_TITLE: "Test",
    DEFAULT_TOKEN_GOAL: 3,
    DEFAULT_MAX_TOKENS: 5,
    DEFAULT_STARTDATE_SHIFT: 2,
    DEFAULT_DEADLINE_SHIFT: 6,
    DEFAULT_VALUE: 1,
    DEFAULT_INVALID_TOKENS: 0
}